policy:
  approval:
    - 'obsidians.io engineer has approved'
  disapproval:
    requires:
      organizations:
        - ObsidianLabs
approval_rules:
  -
    name: 'obsidians.io engineer has approved'
    if:
      targets_branch:
        pattern: ^develop|^master$
    options:
      allow_author: true
      allow_contributor: true
      invalidate_on_push: true
      ignore_update_merges: true
    requires:
      count: 0
      users:
        - qftgtr
        - leonlianght
        - iNorthIsle
