name: Danger CI
on:
  pull_request:

jobs:
  run-danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      
      - name: Use Node.js 16
        uses: actions/setup-node@master
        with:
          node-version: 16
      
      - name: Install deps
        run: yarn install
      
      - name: Run Danger CI
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
